### PR TITLE
12-Remove authentication to non admin users

### PR DESCRIPTION
**Pull request by godfreym**
Issue #12 

## Note:
Most of the users to this site but the recruiter are just the normal non admin users who are not supposed to sign in in order to use the site so this issue will take care of that by adding the authentication **only** to those who needs to be authenticated like the recruiter/admin

## Story:
**AS A Non Admin User** of the site
**I WANT TO** be able to see the job openings, upload my CV and do all of the recruitment stuffs without having to sign up / sign in to the site
**SO THAT** I can skip all the harder part for having to sign in every time I want to use the site

## Acceptance Criteria:
- [x] GIVEN I am the non-admin user and wants to use the site WHEN I access the 3sixd link THEN I SHOULD be able to be landed to its home page WITHOUT having to sign in / sign up
- [x] GIVEN I am the admin user and want to add a company or customize a company THEN I SHOULD be able to do so WHEN I successfully sign on to the site

### CODE REVIEW

**Comment by godfreym** [comment]
@leonardk1 Please Review

**Comment by leonardk1** [comment]
@godfreym :+1:

**Comment by godfreym** [comment]
@arafatm Please Review

**Comment by arafatm** [comment]
@godfreym :+1:

**Pull request merged**
