### PR TITLE
24-Avoid forcing company title to uppercase

### PR DESCRIPTION
**Pull request by godfreym**
Issue #24 

### Story:
AS AN Admin of the site
I WANT to display the site's contents as I entered them when creating a company
SO THAT I can have the sites look intended for the users

### Note:
The company title was forced to be displayed in capital letters even when the admin entered it in small letters, This PR takes care of that by making sure the name will be displayed as entered

### Acceptance Criteria:
- [x] GIVEN I am the site's admin WHEN I enter the company title during adding a new company or updating an existing one THEN I should be see that title the way I entered it

### CODE REVIEW

**Comment by godfreym** [comment]
@leonardk1 Please Review

**Comment by leonardk1** [comment]
@godfreym :+1:

**Comment by godfreym** [comment]
@arafatm Please Review

**Comment by arafatm** [comment]
:+1:

**Pull request merged**
