### PR TITLE
2-Model Structure For Making The Home View Customizable Per Company Requirement

### PR DESCRIPTION
**Pull request by godfreym**
Issue #5 

## Story:

AS A Company/Agent using the 3sixD site
I WANT To be able to customize the site home view
SO THAT I can put my companies info on the site instead of using 3sixD infos

## Acceptance Criteria:
- [x] GIVEN I am the user accessing the 3sixD site WHEN I am using the site as an agent from another company apart from 3sixD THEN I SHOULD be able to customize the home view SO THAT I Can put my company's infos instead of 3sixd's info

## Tasks Involved:
- [x] Create the model to keep track of the various companies info provided on the home view of the site

### CODE REVIEW

**Comment by godfreym** [comment]
@leonardk1 Please Review

**Comment by leonardk1** [comment]
@godfreym I like the minitest, so simple

**Comment by godfreym** [comment]
@leonardk1 Yep sure and they are straight forward than Rspec

**Comment by leonardk1** [comment]
@godfreym the code looks good, maybe you can provide for me in a gist, what the model should look like, so that I can be able to review well

**Comment by godfreym** [comment]
@leonardk1 Please check the `schema` file will tell you what the model should look like

**Comment by godfreym** [comment]
screenshot from 2015-10-29 11 33 14

@leonardk1 From that screen shot above, Find the word
1. 3sixD Consulting - This is the company description for a specific company (every company will have its own description)
2. We create openings - Potential candidates apply for the job - We will hire the succesfully candidate - This is the sub description (each company will have its own)

So those stuffs are editable depending on a company, that is why there is a model Company which will track all the necessary infos for a company starting from its name to description, sub description etc etc

**Comment by leonardk1** [comment]
@godfreym :+1:

**Comment by godfreym** [comment]
@leonardk1 So all the stuffs you see on the home view including the logo, company name, description, social network links etc etc, they will all be editable in a way different companies will be using the same site but each one with its own infos

**Comment by godfreym** [comment]
@arafatm Please review

**Comment by godfreym** [comment]
@arafatm Please Review

**Comment by arafatm** [comment]
@godfreym :+1:

**Pull request merged**
