### PR TITLE
24-Make footer about contents editable

### PR DESCRIPTION
**Pull request by godfreym**
Issue #24 

### Story:
AS AN Admin of the site
I WANT to update the site's contents including the footer about
SO THAT I can track the relevant information concerning the company

### Note:
The about contents at the right hand side of the site's footer is supposed to be editable so that the admin can add his own about contents, This PR takes care of that

### Acceptance Criteria:
- [x] GIVEN I am the site's admin WHEN I update my company's info THEN I should be able to update the footer about as well

### CODE REVIEW

**Comment by godfreym** [comment]
@leonardk1 Please Review

**Comment by leonardk1** [comment]
@godfreym :+1:

**Comment by godfreym** [comment]
@arafatm Please Review

**Comment by godfreym** [comment]
@arafatm Please Review

**Comment by arafatm** [comment]
:+1:

**Pull request merged**
