### PR TITLE
24-Properly configuring font awesome with rails asset pipeline

### PR DESCRIPTION
**Pull request by godfreym**
Issue #24 
### Note:

Font awesome icons for the social links at the bottom right of the site's footer don't render properly to some browsers, This PR tries to resolve by configuring properly the font awesome with rails asset pipeline
### Acceptance Criteria:
- [x] GIVEN I am the user of the site WHEN I access the site THEN I should see the all contents properly as expected

### CODE REVIEW

**Comment by godfreym** [comment]
@leonardk1 Please Review

**Comment by leonardk1** [comment]
@godfreym thats good. 
Have also tried to use the latest version of fontawesome?

**Comment by godfreym** [comment]
@leonardk1 Yes I have now used the latest version of font awesome

**Comment by godfreym** [comment]
@arafatm Please Review

**Comment by arafatm** [comment]
@godfreym have you checked this works? If so, go ahead and merge

**Pull request merged**
