### PR TITLE
1-Integrating recruiter box with 3sixD

### PR DESCRIPTION
**Pull request by godfreym**
Issue #1 

### Story
AS A User (Job seeker or Job poster)
I WANT To see the opening jobs on 3sixD site
SO THAT I can apply for the job I am skilled on

### Task Involved:
- [x] Integrating recruiter box with 3siD so that openings on recruiter box should also appear on 3sixD site

### CODE REVIEW

**Comment by godfreym** [comment]
@leonardk1 Please Review

**Comment by leonardk1** [comment]
@godfreym :+1:

**Comment by godfreym** [comment]
@arafatm Please Review

**Comment by arafatm** [comment]
@godfreym Do you have a heroku deploy yet?

**Comment by godfreym** [comment]
@arafatm not yet! could you please create an account for it so i can deploy

**Comment by arafatm** [comment]
@godfreym you should have access to fstage-3sixd to deploy to on heroku

**Comment by godfreym** [comment]
@arafatm Yep Thanks, already deployed! here we go http://fstage-3sixd.herokuapp.com

**Comment by NashvilleJim** [comment]
just took a quick look and we're off to a great start.  That's just what
I'm after for now.  a clean, simple site structure, and you've integrated
recruiterbox etc just like I need.   Good job Godfrey.

I obviously have to provide some content.  Have some thoughts here that I
may want to chat with you about Arafat. I'm in Ireland for 2 weeks - let me
know when is a good time to catch up.

Thanks,
Jim

On Mon, Oct 26, 2015 at 5:34 AM, Godfrey Mlowe <notifications@github.com>
wrote:

> @arafatm <https://github.com/arafatm> Yep Thanks, already deployed! here
> we go http://fstage-3sixd.herokuapp.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Furaha/3sixd/pull/2#issuecomment-151094711>.
>



-- 
Thank you,
Jim Heffner, CEO
3sixD, Inc.
615.422.7004

**Comment by godfreym** [comment]
Hi Jim,

Let us have a chat hangout tomorrow (Tuesday), how about 1pm my time and
that is probably 10am Ireland time?

Let me know if it will be a good time for you

Thanks,

Godfrey

**Comment by NashvilleJim** [comment]
tomorrow @ 10am sounds good to me.

**Comment by arafatm** [comment]
That's gonna be too early for me :-/

You guys go ahead and chat. Please send me notes and I'll chime in if
needed.

Cheers

**Comment by NashvilleJim** [comment]
Let me give you both my thoughts briefly here, and if you'd like to be a part of the conversation Arafat I'm flexible, or as you said we'll just fill you in afterwards.   

Where I see this site going possibly, is as a service to offer other agencies.  So I'd like from the very beginning to think in those terms and not let the site get ahead of us where we'd need significant refactoring later on.  With that in mind I'd like to move some of the content into config parameters where I can change the company name/address, the tag line, the about me text, the logo too I suppose.  For now that's all but we can continue to put things into tables with the idea it may not be 3sixD but another companies page later.  I assume an authentication layer would therefore be needed too so I can login and edit the config.  and possibly the design can be setup as a theme with more to come later (I'll be focusing a lot on content/devel not so much design as that's not my forte, but let's keep that in mind as well - and your input may be valuable here in terms of abstracting the look-n-feel however that's best done).

I want to keep it simple to start but designed for growth and additional features.  

And as always, please provide any opinions and ideas you may have on this.  I'll want other professional opinions all along.

BTW: is this the right place for these comments?
Jim

**Comment by arafatm** [comment]
Works for me.

@NashvilleJim I suggest opening a new issue for each topic so it's easier to separate concerns. But yeah, GH:issues is definitely the right place for these discussions.

**Comment by godfreym** [comment]
test

**Comment by NashvilleJim** [comment]
Morning Godfrey, I can't make the meeting this morning. Let's reschedule for tomorrow?

Thanks,
Jim

**Comment by godfreym** [comment]
Afternoon Jim, Yeah sure we can reschedule for tomorrow but if you can still make it today later in your evenings? I still have some times for later

Please let me know, Thanks

**Comment by NashvilleJim** [comment]
Hi Godfrey.  Obviously I wasn't available last night. Just got this.  I may be running late today.  Have to run back to the airport for my rental car.  I will email or Chat at you when I return if that's ok?

Jim

**Comment by godfreym** [comment]
@NashvilleJim Hi Jim, It is OK

**Comment by NashvilleJim** [comment]
just sent you gmail chat request.  Message back when you're ready and we'll
do vid chat

On Wed, Oct 28, 2015 at 9:14 AM, Godfrey Mlowe <notifications@github.com>
wrote:

> @NashvilleJim <https://github.com/NashvilleJim> Hi Jim, It is OK
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Furaha/3sixd/pull/2#issuecomment-151775312>.
>



-- 
Thank you,
Jim Heffner, CEO
3sixD, Inc.
615.422.7004

**Comment by godfreym** [comment]
Hi Jim,

I am ready for the chat now

Thanks

**Comment by NashvilleJim** [comment]
​I sent a google hangouts request.  I don't know if you have to check your
gmail and accept my invitation but check email now and see.​

On Wed, Oct 28, 2015 at 3:14 PM, Godfrey Mlowe <notifications@github.com>
wrote:

> Hi Jim,
>
> I am ready for the chat now
>
> Thanks
>
> On Wed, Oct 28, 2015 at 2:58 PM, Jim Heffner <notifications@github.com>
> wrote:
>
> > just sent you gmail chat request. Message back when you're ready and
> we'll
> > do vid chat
> >
> > On Wed, Oct 28, 2015 at 9:14 AM, Godfrey Mlowe <notifications@github.com
> >
> > wrote:
> >
> > > @NashvilleJim <https://github.com/NashvilleJim> Hi Jim, It is OK
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/Furaha/3sixd/pull/2#issuecomment-151775312>.
> > >
> >
> >
> >
> > --
> > Thank you,
> > Jim Heffner, CEO
> > 3sixD, Inc.
> > 615.422.7004
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Furaha/3sixd/pull/2#issuecomment-151820323>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Furaha/3sixd/pull/2#issuecomment-151877699>.
>



-- 
Thank you,
Jim Heffner, CEO
3sixD, Inc.
615.422.7004

**Comment by godfreym** [comment]
@NashvilleJim I have checked my email and haven't seen a hangout request, Please Send it again

**Pull request merged**
